//! `SeaORM` Entity. Generated by sea-orm-codegen 0.11.3

pub use super::annotation::Entity as Annotation;
pub use super::assign::Entity as Assign;
pub use super::catalog::Entity as Catalog;
pub use super::image::Entity as Image;
pub use super::schema::Entity as Schema;
pub use super::task::Entity as Task;
