//! `SeaORM` Entity. Generated by sea-orm-codegen 0.11.3

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "task")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: String,
    pub schema_id: String,
    pub catalog_id: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::assign::Entity")]
    Assign,
    #[sea_orm(
        belongs_to = "super::catalog::Entity",
        from = "Column::SchemaId",
        to = "super::catalog::Column::Id",
        on_update = "Restrict",
        on_delete = "Restrict"
    )]
    Catalog,
    #[sea_orm(
        belongs_to = "super::schema::Entity",
        from = "Column::SchemaId",
        to = "super::schema::Column::Id",
        on_update = "Restrict",
        on_delete = "Restrict"
    )]
    Schema,
}

impl Related<super::assign::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Assign.def()
    }
}

impl Related<super::catalog::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Catalog.def()
    }
}

impl Related<super::schema::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Schema.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
